Repository HugoGit-Hub/CashManager, pull requests merged in 2023-12, with the labels that each got.

#39 Create dotnet.yml
  .github/workflows/dotnet.yml
Labels: enhancement

#41 Create sonar.yml
  .github/workflows/sonar.yml
Labels: enhancement

#43 Create dart.yml
  .github/workflows/dart.yml
  cashmanagerapp/test/widget_test.dart
Labels: enhancement

#50 Feature/unit test banking account
  .github/workflows/banking.yml
  .github/workflows/consumer.yml
  .github/workflows/dart.yml
  .github/workflows/dotnet.yml
  .github/workflows/nextjs.yml
  .github/workflows/sonar.yml
  CashManager.Banking.sln
  CashManager.Banking/CashManager.Banking.Api/CashManager.Banking.Api.csproj
  CashManager.Banking/CashManager.Banking.Api/Configuration/AssemblyMarker.cs
  CashManager.Banking/CashManager.Banking.Api/Controllers/AccountController.cs
  CashManager.Banking/CashManager.Banking.Api/Program.cs
  CashManager.Banking/CashManager.Banking.Application/Accounts/AccountResponse.cs
  CashManager.Banking/CashManager.Banking.Application/Accounts/GetAccountByCurrentUser/GetAccountsByCurrentUserQuery.cs
  CashManager.Banking/CashManager.Banking.Application/Accounts/GetAccountByCurrentUser/GetAccountsByCurrentUserQueryHandler.cs
  CashManager.Banking/CashManager.Banking.Application/CashManager.Banking.Application.csproj
  CashManager.Banking/CashManager.Banking.Application/DependencyInjection.cs
  CashManager.Banking/CashManager.Banking.Domain/Accounts/Account.cs
  CashManager.Banking/CashManager.Banking.Domain/Accounts/AccoutBase.cs
  CashManager.Banking/CashManager.Banking.Test/Account/AccountControllerShould.cs
  CashManager.Banking/CashManager.Banking.Test/Account/AccountResponseShould.cs
  CashManager.Banking/CashManager.Banking.Test/Account/GetAccountsByCurrentUserQueryHandlerHandleShould.cs
  CashManager.Banking/CashManager.Banking.Test/CashManager.Banking.Test.csproj
  CashManager.Banking/CashManager.Banking.Test/Helpers/StringHelper.cs
  CashManager.Banking/CashManager.Banking.Test/Usings.cs
Labels: enhancement

#51 Feature/docker
  CashManager.Banking/CashManager.Banking.Api/Dockerfile
  CashManager.Banking/CashManager.Banking.Api/appsettings.Development.json
  CashManager.Banking/docker-compose.yml
  cashmanager-banking-web/app/utils/FetchBanking.ts
Labels: bug

#53 Feature/introductionslide
  cashmanagerapp/lib/images/intro1.png
  cashmanagerapp/lib/images/intro2.png
  cashmanagerapp/lib/images/intro3.png
  cashmanagerapp/lib/main.dart
  cashmanagerapp/lib/pages/introductionPages/introduction.dart
  cashmanagerapp/lib/widgets/app_large_text.dart
  cashmanagerapp/lib/widgets/app_text.dart
  cashmanagerapp/pubspec.yaml
Labels: enhancement

#54 Feature/detail product page
  cashmanagerapp/lib/main.dart
  cashmanagerapp/lib/pages/detailPages/detail.dart
  cashmanagerapp/lib/widgets/button_add_to_cart.dart
  cashmanagerapp/lib/widgets/button_like.dart
  cashmanagerapp/lib/widgets/quantity_selector.dart
Labels: enhancement

#52 Feature/general docker
  .gitignore
  CashManager.Banking/CashManager.Banking.Api/Dockerfile
  CashManager.Banking/docker-compose.yml
  CashManager.Consumer/CashManager.Consumer.Api/Dockerfile
  CashManager.Consumer/CashManager.Consumer.Api/appsettings.Development.json
  cashmanager-banking-web/Dockerfile
  cashmanagerapp/Dockerfile
  docker-compose.yml
Labels: enhancement

#55 Feature/login pages
  cashmanagerapp/lib/images/login.jpg
  cashmanagerapp/lib/images/register.jpg
  cashmanagerapp/lib/main.dart
  cashmanagerapp/lib/pages/loginPages/login.dart
  cashmanagerapp/lib/pages/loginPages/register.dart
  cashmanagerapp/pubspec.yaml
Labels: enhancement

#57 SonarCloud Consumer analyse
  .github/workflows/sonar.yml
Labels: enhancement

#60 Feature/adapt article workflow
  CashManager.Consumer/CashManager.Consumer.Api/Controllers/ArticleController.cs
  CashManager.Consumer/CashManager.Consumer.Application/Articles/GetArticleById/GetArticleByIdQuery.cs
  CashManager.Consumer/CashManager.Consumer.Application/Articles/GetArticleById/GetArticleByIdQueryHandler.cs
  CashManager.Consumer/CashManager.Consumer.Application/Articles/GetArticles/GetArticlesQuery.cs
  CashManager.Consumer/CashManager.Consumer.Application/Articles/GetArticles/GetArticlesQueryHandler.cs
  CashManager.Consumer/CashManager.Consumer.Application/DependencyInjection.cs
Labels: enhancement

#62 Feature/authentication and authorization middlewares
  CashManager.Consumer/CashManager.Consumer.Api/CashManager.Consumer.Api.csproj
  CashManager.Consumer/CashManager.Consumer.Api/Controllers/ArticleController.cs
  CashManager.Consumer/CashManager.Consumer.Api/Program.cs
Labels: enhancement

#64 Feature/call api flutter
  cashmanagerapp/lib/pages/loginPages/register.dart
  cashmanagerapp/lib/services/authenticationservice.dart
  cashmanagerapp/pubspec.lock
  cashmanagerapp/pubspec.yaml
Labels: enhancement

#66 Feature/get all cart items
  CashManager.Consumer/CashManager.Consumer.Api/Controllers/ShoppingSessionController.cs
  CashManager.Consumer/CashManager.Consumer.Application/DependencyInjection.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/GetShoppingSessionCartItems/GetShoppingSessionCartItemsQuery.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/GetShoppingSessionCartItems/GetShoppingSessionCartItemsQueryHandler.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/GetShoppingSessionCartItems/GetShoppingSessionCartItemsResponse.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/IShoppingSessionRepository.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/ShoppingSessionService.cs
  CashManager.Consumer/CashManager.Consumer.Domain/ShoppingSessions/IShoppingSessionService.cs
  CashManager.Consumer/CashManager.Consumer.Domain/ShoppingSessions/ShoppingSessionErrors.cs
  CashManager.Consumer/CashManager.Consumer.Infrastructure/DependencyInjection.cs
  CashManager.Consumer/CashManager.Consumer.Infrastructure/ShoppingSessions/ShoppingSessionRepository.cs
Labels: enhancement

#68 Feature/register
  cashmanagerapp/lib/pages/loginPages/login.dart
  cashmanagerapp/lib/pages/loginPages/register.dart
Labels: enhancement

#67 Feature/create cart item
  CashManager.Consumer/CashManager.Consumer.Api/Controllers/CartItemController.cs
  CashManager.Consumer/CashManager.Consumer.Application/CartItems/CartItemService.cs
  CashManager.Consumer/CashManager.Consumer.Application/CartItems/CreateCartItem/CreateCartItemCommand.cs
  CashManager.Consumer/CashManager.Consumer.Application/CartItems/CreateCartItem/CreateCartItemCommandHandler.cs
  CashManager.Consumer/CashManager.Consumer.Application/CartItems/CreateCartItem/CreateCartItemRequest.cs
  CashManager.Consumer/CashManager.Consumer.Application/CartItems/CreateCartItem/CreateCartItemResponse.cs
  CashManager.Consumer/CashManager.Consumer.Application/CartItems/ICartItemRepository.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/GetShoppingSessionCartItems/GetShoppingSessionCartItemsQueryHandler.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/IShoppingSessionRepository.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/ShoppingSessionService.cs
  CashManager.Consumer/CashManager.Consumer.Domain/CartItems/ICartItemService.cs
  CashManager.Consumer/CashManager.Consumer.Domain/ShoppingSessions/IShoppingSessionService.cs
  CashManager.Consumer/CashManager.Consumer.Infrastructure/CartItems/CartItemRepository.cs
  CashManager.Consumer/CashManager.Consumer.Infrastructure/ShoppingSessions/ShoppingSessionRepository.cs
Labels: enhancement

#70 Feature/fix shopping session creation
  CashManager.Consumer/CashManager.Consumer.Api/Controllers/ShoppingSessionController.cs
  CashManager.Consumer/CashManager.Consumer.Application/CartItems/CreateCartItem/CreateCartItemCommandHandler.cs
  CashManager.Consumer/CashManager.Consumer.Application/CartItems/CreateCartItem/CreateCartItemRequest.cs
  CashManager.Consumer/CashManager.Consumer.Application/DependencyInjection.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/CreateShoppingSession/CreateShoppingSessionCommand.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/CreateShoppingSession/CreateShoppingSessionCommandHandler.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/IShoppingSessionRepository.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/ShoppingSessionService.cs
  CashManager.Consumer/CashManager.Consumer.Domain/ShoppingSessions/IShoppingSessionService.cs
  CashManager.Consumer/CashManager.Consumer.Infrastructure/ShoppingSessions/ShoppingSessionRepository.cs
Labels: fix

#71 Close current ShoppingSession at Transaction
  CashManager.Consumer/CashManager.Consumer.Application/Transactions/CreateTransaction/CreateTransactionCommandHandler.cs
Labels: enhancement

#75 Feature/delete cart items from shopping session
  CashManager.Consumer/CashManager.Consumer.Api/Controllers/ShoppingSessionController.cs
  CashManager.Consumer/CashManager.Consumer.Application/DependencyInjection.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/DeleteCartItemFromCurrentShoppingSession/DeleteCartItemFromCurrentShoppingSessionCommand.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/DeleteCartItemFromCurrentShoppingSession/DeleteCartItemFromCurrentShoppingSessionCommandHandler.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/IShoppingSessionRepository.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/ShoppingSessionService.cs
  CashManager.Consumer/CashManager.Consumer.Domain/ShoppingSessions/IShoppingSessionService.cs
  CashManager.Consumer/CashManager.Consumer.Infrastructure/ShoppingSessions/ShoppingSessionRepository.cs
Labels: enhancement

#77 Feature/scan
  cashmanagerapp/android/app/build.gradle
  cashmanagerapp/lib/images/unknown.jpg
  cashmanagerapp/lib/main.dart
  cashmanagerapp/lib/pages/detailPages/detail.dart
  cashmanagerapp/lib/pages/loginPages/login.dart
  cashmanagerapp/lib/pages/scanPages/scan_home.dart
  cashmanagerapp/lib/pages/scanPages/scanhome.dart
  cashmanagerapp/lib/services/articleservice.dart
  cashmanagerapp/pubspec.lock
  cashmanagerapp/pubspec.yaml
Labels: enhancement, fix

#82 Feature/redirection detail page
  cashmanagerapp/lib/main.dart
  cashmanagerapp/lib/models/cartitemmodel.dart
Labels: enhancement

#83 Feature/add to cart
  cashmanagerapp/lib/pages/detailPages/detail.dart
  cashmanagerapp/lib/services/cartservice.dart
  cashmanagerapp/lib/widgets/button_add_to_cart.dart
Labels: enhancement

#84 Feature/pages transaction
  cashmanagerapp/lib/images/Creditcard.png
  cashmanagerapp/lib/images/check.png
  cashmanagerapp/lib/main.dart
  cashmanagerapp/lib/pages/checkoutPages/paiement.dart
  cashmanagerapp/pubspec.yaml
Labels: enhancement

#85 Feature/cart page
  cashmanagerapp/lib/pages/cartPages/cart.dart
  cashmanagerapp/lib/pages/checkoutPages/paiement.dart
  cashmanagerapp/lib/pages/detailPages/detail.dart
  cashmanagerapp/lib/widgets/button_place_order.dart
Labels: enhancement

#86 Feature/liste article
  cashmanagerapp/lib/main.dart
  cashmanagerapp/lib/pages/articlesPages/listarticles.dart
  cashmanagerapp/pubspec.yaml
Labels: enhancement

#87 Feature/fix&refactoproject
  cashmanagerapp/lib/main.dart
  cashmanagerapp/lib/models/article_model.dart
  cashmanagerapp/lib/models/cartitem_model.dart
  cashmanagerapp/lib/pages/articlesPages/list_articles.dart
  cashmanagerapp/lib/pages/cartPages/cart.dart
  cashmanagerapp/lib/pages/checkoutPages/paiement.dart
  cashmanagerapp/lib/pages/detailPages/detail.dart
  cashmanagerapp/lib/pages/loginPages/login.dart
  cashmanagerapp/lib/pages/loginPages/register.dart
  cashmanagerapp/lib/pages/scanPages/scanhome.dart
  cashmanagerapp/lib/services/article_service.dart
  cashmanagerapp/lib/services/authentication_service.dart
  cashmanagerapp/lib/services/cart_service.dart
  cashmanagerapp/lib/widgets/button_add_to_cart.dart
  cashmanagerapp/lib/widgets/quantity_selector.dart
Labels: refactoring, fix

#88 Refacto translate french
  cashmanagerapp/lib/main.dart
  cashmanagerapp/lib/pages/cartPages/cart.dart
  cashmanagerapp/lib/pages/categoryPages/category.dart
  cashmanagerapp/lib/pages/categoryPages/category_dairy.dart
  cashmanagerapp/lib/pages/categoryPages/category_fruit.dart
  cashmanagerapp/lib/pages/categoryPages/category_vegetable.dart
  cashmanagerapp/lib/pages/checkoutPages/paiement.dart
  cashmanagerapp/lib/pages/detailPages/detail.dart
  cashmanagerapp/lib/pages/loginPages/login.dart
  cashmanagerapp/lib/pages/loginPages/register.dart
  cashmanagerapp/lib/pages/scanPages/scanhome.dart
  cashmanagerapp/lib/widgets/button_place_order.dart
Labels: refactoring

#89 Add id in cartItemResponse
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/GetCurrentOpenedShoppingSessionCartItems/GetShoppingSessionCartItemsQueryHandler.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/GetCurrentOpenedShoppingSessionCartItems/GetShoppingSessionCartItemsResponse.cs
Labels: enhancement

#91 Feature/transaction service
  cashmanagerapp/lib/main.dart
  cashmanagerapp/lib/pages/checkoutPages/paiement.dart
  cashmanagerapp/lib/pages/scanPages/scanhome.dart
  cashmanagerapp/lib/services/transactionservice.dart
Labels: enhancement, fix

#92 Feature/fix delete article item substraction
  CashManager.Consumer/CashManager.Consumer.Application/CartItems/CartItemService.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/DeleteCartItemFromCurrentShoppingSession/DeleteCartItemFromCurrentShoppingSessionCommandHandler.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/ShoppingSessionService.cs
  CashManager.Consumer/CashManager.Consumer.Application/ShoppingSessions/UpdateCartItemFromCurrentShoppingSession/UpdateCartItemFromCurrentShoppingSessionCommandHandler.cs
  CashManager.Consumer/CashManager.Consumer.Domain/ShoppingSessions/IShoppingSessionService.cs
Labels: fix
